### ISSUE TITLE
not compiling with Zig 0.13

### ISSUE THREAD

**Issue by Epliz** [Snektron/goniometer#1]
Hi,

Thanks for working on such interesting project
When I tried to compile with Zig 0.13.0,I however got some issues. I think it might be good to indicate in the readme what Zig version is supposed to work.

I got it to work by modifying the build file to 
```zig
const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    const lib = b.addSharedLibrary(.{
        .name = "goniometer",
        .root_source_file = b.path("src/main.zig"),
        .target = target,
        .optimize = optimize,
    });
    lib.linkLibC();
    lib.addIncludePath(.{.cwd_relative= "/opt/rocm/include"});
    b.installArtifact(lib);

    const rgp_dump = b.addExecutable(.{
        .name = "rgp-dump",
        .root_source_file = b.path("src/rgp_dump.zig"),
        .target = target,
        .optimize = optimize,
    });
    b.installArtifact(rgp_dump);

    const rgp_cut = b.addExecutable(.{
        .name = "rgp-cut",
        .root_source_file = b.path("src/rgp_cut.zig"),
        .target = target,
        .optimize = optimize,
    });
    b.installArtifact(rgp_cut);
}
```

I however have no idea if that's what it should be as I have zero knowledge about Zig.

Thanks again for this work.
Best,
Epliz

**Comment by Snektron** [comment]
Hi, Zig is kind of a moving target and has changed a bit in the meantime. I believe that it used some random build from the master branch of 0.10, so 0.11 might work. It should be relatively straight forward to update to 0.13, though, for someone who has some knowledge of Zig. It shouldn't take too long, I can do that for you in a bit.

**Comment by Snektron** [comment]
Looks like your chances were correct already :) I've pushed them and added a mention about the version in the readme.
